version: 0.2
phases:
  install:
    commands:
      - |
        if ! command -v node >/dev/null 2>&1; then
          curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash - || true
          sudo yum install -y nodejs || sudo dnf install -y nodejs || true
          if ! command -v node >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm
          fi
        fi
      - node -v
      - npm -v
  pre_build:
    commands:
      - npm ci || npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - appspec.yml
    - codedeploy_scripts/**/*
    - build/**/*
  discard-paths: no
