import React from "react";

export default function AiNotice() {
  return (
    <div
      role="note"
      aria-live="polite"
      style={{
        fontSize: 12,
        padding: "10px 12px",
        border: "1px solid #e5e7eb",
        borderRadius: 8,
        background: "#f9fafb",
        color: "#374151",
        margin: "12px 0"
      }}
    >
      <strong>Friendly heads-up:</strong> Answers here are generated by AI to help you learn.
      AI can miss things, so avoid sharing personal or sensitive info and double-check any
      important details with reliable sources.
    </div>
  );
}
