import React from "react";

export default function AiNotice() {
  return (
    <div
      style={{
        fontSize: 12,
        padding: "10px 12px",
        border: "1px solid #e5e7eb",
        borderRadius: 8,
        background: "#f9fafb",
        color: "#374151",
        margin: "12px 0",
      }}
    >
      <strong>Note:</strong>{" "}
      Answers here are generated by AI to help you learn. AI can miss things, so
      double-check details with sources provided by your instructor. Avoid
      sharing sensitive information.
      <br />
      <span style={{ fontSize: 11, color: "#6b7280" }}>
        © 2025. All rights reserved.
      </span>
    </div>
  );
}
